#!/bin/sh
#
# btconnect - A script to connect to paired bluetooth devices
#

set -e

paired=$(bluetoothctl devices)
selected=$(echo "${paired}" | awk '{ print $3 }' | dmenu -l 10)
mac=$(echo "$paired" | grep "$selected" | awk '{ print $2 }')

bluetoothctl power on
bluetoothctl connect "$mac"

